export { default as Navbar } from './Navbar.vue'
export { default as Hero } from './Hero.vue'
export { default as Companies } from './Companies.vue'
export { default as Jumpstart } from './Jumpstart.vue'
export { default as WhyUse } from './WhyUse.vue'
export { default as GetTheApp } from './GetTheApp.vue'
export { default as Plans } from './Plans.vue'
export { default as Footer } from './Footer.vue'
